# Use the official lightweight Node.js 14 image.
# https://hub.docker.com/_/node
FROM node:18-alpine

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json (if available)
COPY package*.json ./

# Install the application dependencies
# If you're using yarn:
# RUN yarn install --production
RUN npm install --production

# Copy the application files
COPY . .

# Expose the application on port 3000
EXPOSE 3000

# Run the application
CMD [ "node", "server.js" ]
